# Generated by Django 4.1.1 on 2022-10-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='num_stars',
            field=models.IntegerField(choices=[(1, 'WORST'), (2, 'BAD'), (3, 'NOT BAD'), (4, 'GOOD'), (5, 'EXCELLENT')]),
        ),
    ]
